### ISSUE TITLE
asl-say should be able to speak the current weather conditions

### ISSUE THREAD

**Issue by Allan-N** [AllStarLink/ASL3#69]
We have a number of users who would like their nodes to be able to report the current weather conditions.  We should investigate providing this functionality.

**Comment by drsm0ke** [comment]
To have the temperature announced at the top of the hour in addition to the time.
I would like to know if this can be done in the new ASL3. as an [enhancement](https://github.com/AllStarLink/ASL3/labels/enhancement) to ASL3?
I have the time working but no temperature announcements.
Thanks in Advance
Bob - W0NQX

**Comment by jxmx** [comment]
CLosing in favor of @KB4MDD's solution.
