### ISSUE TITLE
Add support for Hotspot COR LED

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/ASL3#70]
This issue is to create an easy way for users to add COR LED support to their hot spot via the asl-menu.
- Add [event-hs_led] stanza to default rep.conf \[node-main\]\(!\) template. Obviously, all new installs then come with it. 
```
[event-hs_led]
cop,62,GPIO4:1 = c|t|RPT_RXKEYED
cop,62,GPIO4:0 = c|f|RPT_RXKEYED
```
- Write patch or script to add [event-hs_led] to rpt.conf \[node-main\]\(!\) template where it does not exist upon apt update and apt upgrade.
- Modify asl-menu to add selection to add `events = event-hs_led` to selected node stanza.

**Comment by KB4MDD** [comment]
I am sorry - I did not realize this was already in process.  I created https://github.com/AllStarLink/app_rpt/pull/370.  To add these to the defaults.

**Comment by jxmx** [comment]
See https://github.com/AllStarLink/app_rpt/pull/370
