### ISSUE TITLE
app_rpt:  Add support for rotating id's

### ISSUE THREAD

**Issue by KB4MDD** [AllStarLink/ASL3#8]
Change app_rpt to support rotating id's like the tail messages.

**Comment by Allan-N** [comment]
Gotta ask ... What is a rotating ID?

**Comment by KB4MDD** [comment]
This is the ability to have different voice id's.  This was something that the old ACC controllers supported.  Our old acc controller had, I think 3, different voice id's that would play - if someone keyed on top of them it would revert to morse.

**Comment by tsawyer** [comment]
In case it's unknown, the tail message can play any number of rotating messages.

**Comment by jxmx** [comment]
From discussion, this feature already exists
