### ISSUE TITLE
Make ASL node (astdb.txt) info available via [expanded] DNS "TXT" records

### ISSUE THREAD

**Issue by Allan-N** [AllStarLink/ASL3#87]
We have been generating the "astdb.txt" database for a while and many nodes are regularly downloading the file, mostly for the benefit of web monitoring applications (e.g. Allmon, Supermon, AllScan, etc).

As we have done for the node database, "rpt_extnodes", we should look to migrate people from downloading the full DB and have them query DNS for the per-node information.

Note: this will require some backend (DNS) support and the addition of sample code and/or commands to query the information.

**Comment by jxmx** [comment]
Added to the **Infrastructure To Do List** canvas.
