### ISSUE TITLE
Add Time/Weather Script

### ISSUE THREAD

**Issue by W9IKU** [AllStarLink/ASL3#96]
I would like to see a script that will announce the time and weather on ASL3.

Thank you!

**Comment by jxmx** [comment]
This is not a "bug". The script 'asl-say' will announce the time if you want to create a cron job to do it. There are other projects that work on reporting the weather. This is not functionality planned for core ASL3.

**Comment by jxmx** [comment]
https://github.com/AllStarLink/ASL3/issues/69
